name: MissionGameAware
main: me.dordsor21.MissionGameAware.MissionGameAware
version: 1.0
api-version: 1.16
author: dordsor21
description: MissionGameAware
commands:
  MissionGameAware:
    description: MissionGameAware.
    aliases: [ mga ]
  queuetwist:
    description: MissionGameAware.
    aliases: [ qt ]
  canceltwist:
    description: MissionGameAware.
    aliases: [ ct ]
  stopchallenge:
    description: MissionGameAware.
    aliases: [ sc ]
  queuechallenge:
    description: MissionGameAware.
    aliases: [ qc ]
  survchallenge:
    description: MissionGameAware.
    aliases: [ sc ]
